#include <doctest/doctest.h>

#include <cstddef>
#include <fstream>
#include <string>
#include <algorithm>
#include <vector>

#include "core/gguf/reader.h"

// The file arrives from a CDN. These are the tests that matter: each case must
// produce a NAMED error and must not read outside the buffer.
//
// Every fixture is generated by tools/make_fixture_gguf.py as one deliberate
// mutation of the valid file, so what is wrong with each is auditable rather
// than buried in a hand-edited binary.
using namespace bllm::gguf;

namespace {

ReadError parse_fixture(const std::string& name) {
    const std::string path = std::string(BLLM_GGUF_FIXTURE_DIR) + "/" + name + ".gguf";
    std::ifstream in(path, std::ios::binary);
    REQUIRE_MESSAGE(in.is_open(), "missing fixture: " << path);
    std::vector<char> raw((std::istreambuf_iterator<char>(in)),
                          std::istreambuf_iterator<char>());
    std::vector<std::byte> bytes(raw.size());
    for (std::size_t i = 0; i < raw.size(); ++i) {
        bytes[i] = static_cast<std::byte>(static_cast<unsigned char>(raw[i]));
    }
    MemoryByteSource source{bytes};
    Reader reader{source};
    return reader.parse();
}

}  // namespace

TEST_CASE("malformed inputs each fail with their own named error") {
    CHECK(parse_fixture("bad_magic") == ReadError::BadMagic);
    CHECK(parse_fixture("bad_version") == ReadError::UnsupportedVersion);
    CHECK(parse_fixture("truncated_header") == ReadError::ShortRead);
    CHECK(parse_fixture("tensor_count_too_large") == ReadError::CountTooLarge);
    CHECK(parse_fixture("metadata_count_lies") == ReadError::ShortRead);
    CHECK(parse_fixture("negative_dimension") == ReadError::NegativeDimension);
    CHECK(parse_fixture("unknown_tensor_type") == ReadError::UnknownTensorType);
    CHECK(parse_fixture("not_block_aligned") == ReadError::UnsupportedTensorType);
    CHECK(parse_fixture("duplicate_tensor_name") == ReadError::DuplicateTensorName);
    CHECK(parse_fixture("nested_array") == ReadError::NestedArray);
    CHECK(parse_fixture("unknown_value_type") == ReadError::UnknownValueType);
    CHECK(parse_fixture("offset_past_eof") == ReadError::TensorDataOutOfBounds);
    CHECK(parse_fixture("data_truncated") == ReadError::TensorDataOutOfBounds);
    // The wrap case: absolute offset arithmetic must be refused, not computed.
    CHECK(parse_fixture("offset_overflow") == ReadError::OffsetOverflow);
}

TEST_CASE("no malformed case is reported as success") {
    // The property that matters more than any individual mapping: nothing
    // deliberately broken parses cleanly.
    for (const char* name : {"bad_magic", "bad_version", "truncated_header",
                             "tensor_count_too_large", "metadata_count_lies",
                             "negative_dimension", "unknown_tensor_type",
                             "not_block_aligned", "duplicate_tensor_name",
                             "nested_array", "unknown_value_type",
                             "offset_past_eof", "data_truncated",
                             "offset_overflow"}) {
        CAPTURE(name);
        CHECK(parse_fixture(name) != ReadError::Ok);
    }
}

TEST_CASE("an empty source fails rather than reading anything") {
    std::vector<std::byte> empty;
    MemoryByteSource source{empty};
    Reader reader{source};
    CHECK(reader.parse() == ReadError::ShortRead);
    CHECK(source.size() == 0);
}

TEST_CASE("every truncation of a valid file fails, none read out of bounds") {
    // Cuts the valid fixture at every length. Any prefix is malformed; the
    // reader must say so rather than walk past the end. This is the case a
    // fixed set of hand-made fixtures cannot cover.
    const std::string path = std::string(BLLM_GGUF_FIXTURE_DIR) + "/valid.gguf";
    std::ifstream in(path, std::ios::binary);
    REQUIRE(in.is_open());
    std::vector<char> raw((std::istreambuf_iterator<char>(in)),
                          std::istreambuf_iterator<char>());
    std::vector<std::byte> full(raw.size());
    for (std::size_t i = 0; i < raw.size(); ++i) {
        full[i] = static_cast<std::byte>(static_cast<unsigned char>(raw[i]));
    }

    // Where the last declared byte of tensor data sits. A cut at or beyond it
    // removes only trailing padding, which is not part of any declared region
    // — the reader is right to accept that. A cut below it removes bytes a
    // tensor claims, and must fail.
    std::uint64_t last_declared_byte = 0;
    {
        MemoryByteSource whole{full};
        Reader reader{whole};
        REQUIRE(reader.parse() == ReadError::Ok);
        for (const auto& t : reader.tensors()) {
            last_declared_byte = std::max(last_declared_byte, t.data_offset + t.data_length);
        }
        REQUIRE(last_declared_byte > 0);
        REQUIRE(last_declared_byte < full.size());   // there IS trailing padding
    }

    std::size_t wrongly_accepted = 0;
    for (std::size_t cut = 0; cut < last_declared_byte; ++cut) {
        std::span<const std::byte> prefix{full.data(), cut};
        MemoryByteSource source{prefix};
        Reader reader{source};
        if (reader.parse() == ReadError::Ok) {
            ++wrongly_accepted;
        }
    }
    // Every prefix that cuts into declared data must be rejected.
    CHECK(wrongly_accepted == 0);
}

TEST_CASE("error strings are distinct and non-empty") {
    CHECK(to_string(ReadError::BadMagic) != to_string(ReadError::ShortRead));
    CHECK_FALSE(to_string(ReadError::TensorDataOutOfBounds).empty());
}
