#pragma once

#include <cstdint>
#include <span>
#include <string_view>

#include "core/tokenizer/unicode.h"

namespace bllm::tokenizer::unicode_tables {

// The Unicode Character Database tables the tokenizer needs, generated by
// tools/make_unicode_tables.py into unicode_tables.cpp. Each table is sorted
// by code point and its entries do not overlap, so it is searched by
// bisection. Each is reached through a function, never a global object, so no
// table depends on another translation unit's initialisation.
//
// Optimization (browser): constexpr data lands in the module's read-only
// segment, so loading the module does no work to build it (WASM.7).
// Optimization (practice): contiguous sorted ranges, about ten comparisons a
// lookup (CACHE.3). ICU goes further, with compact tries.

struct ClassRange {
    char32_t first;
    char32_t last;
    CharClass char_class;
};

// Code points whose canonical combining class is not 0.
struct CombiningRange {
    char32_t first;
    char32_t last;
    std::uint8_t combining_class;
};

// A character's full canonical decomposition: `length` code points of
// decomposition_pool() from `start`. Hangul syllables are not listed; their
// decomposition is arithmetic.
struct Decomposition {
    char32_t code_point;
    std::uint16_t start;
    std::uint16_t length;
};

// A canonical composition: `first` followed by `second` composes to
// `composite`. Characters excluded from composition are not listed.
struct Composition {
    char32_t first;
    char32_t second;
    char32_t composite;
};

[[nodiscard]] std::string_view version() noexcept;
[[nodiscard]] std::span<const ClassRange> classes() noexcept;
[[nodiscard]] std::span<const CombiningRange> combining() noexcept;
[[nodiscard]] std::span<const Decomposition> decompositions() noexcept;
[[nodiscard]] std::span<const char32_t> decomposition_pool() noexcept;
[[nodiscard]] std::span<const Composition> compositions() noexcept;

}  // namespace bllm::tokenizer::unicode_tables
