#!/usr/bin/env python3
"""Generates src/core/tokenizer/unicode_tables.cpp from the Unicode Character
Database.

The tokenizer classifies and normalizes text with these tables, compiled in,
so every browser treats the same text the same way; JavaScript's \\p{...}
classes follow each browser's own Unicode version. The source files are
fetched for one Unicode version and pinned by SHA-256.

The tables:
  - character classes, as the split patterns test them: \\p{L} (general
    category L*), \\p{N} (N*), and \\s (the White_Space property, which is
    what the reference tokenizers' regex engines mean by \\s);
  - canonical combining classes, for NFC's reordering;
  - full canonical decompositions, Hangul syllables excepted (they are
    algorithmic);
  - canonical compositions: every two-character canonical decomposition whose
    character is not excluded from composition.

Needs network access. Not run in CI; its output is committed.

    python3 tools/make_unicode_tables.py src/core/tokenizer/unicode_tables.cpp
"""
import hashlib
import sys
import urllib.request

VERSION = "16.0.0"
SOURCES = {
    "UnicodeData.txt": "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f",
    "PropList.txt": "53d614508e2a0b2305a8aa21cd60d993de9326cdf65993660dfcce4503548583",
    "DerivedNormalizationProps.txt": "4d4c03892dea9146d674b686e495df2d55a28d071ac474041d73518f887abddc",
}
MAX_CODE_POINT = 0x10FFFF
HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3


def fetch(name):
    url = f"https://www.unicode.org/Public/{VERSION}/ucd/{name}"
    with urllib.request.urlopen(url) as response:
        data = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SOURCES[name]:
        sys.exit(f"{name}: SHA-256 {digest} does not match the pinned {SOURCES[name]}")
    return data.decode("utf-8")


def rows(text):
    """The data lines of a UCD file, comments stripped, fields split."""
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            yield [field.strip() for field in line.split(";")]


def code_points(field):
    """'0041' or '0041..005A', as a range."""
    first, _, last = field.partition("..")
    return range(int(first, 16), int(last or first, 16) + 1)


def unicode_data(text):
    """{code point: (general category, combining class, decomposition field)}.
    A range given as <..., First> and <..., Last> rows covers every point
    between."""
    entries, first = {}, None
    for fields in rows(text):
        point, name = int(fields[0], 16), fields[1]
        value = (fields[2], int(fields[3]), fields[5])
        if name.endswith(", First>"):
            first = point
        elif name.endswith(", Last>"):
            for p in range(first, point + 1):
                entries[p] = value
        else:
            entries[point] = value
    return entries


def property_points(text, name):
    return {p for fields in rows(text) if fields[1] == name for p in code_points(fields[0])}


def ranges(value_of):
    """Runs of consecutive code points with the same value, other than None."""
    out, start, current = [], 0, None
    for p in range(MAX_CODE_POINT + 2):
        value = value_of(p) if p <= MAX_CODE_POINT else None
        if value != current:
            if current is not None:
                out.append((start, p - 1, current))
            start, current = p, value
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <out.cpp>")
    data = unicode_data(fetch("UnicodeData.txt"))
    white_space = property_points(fetch("PropList.txt"), "White_Space")
    excluded = property_points(fetch("DerivedNormalizationProps.txt"), "Full_Composition_Exclusion")

    def char_class(p):
        if p in white_space:
            return "Whitespace"
        category = data.get(p, ("Cn", 0, ""))[0]
        return {"L": "Letter", "N": "Number"}.get(category[0])

    classes = ranges(char_class)
    combining = ranges(lambda p: data.get(p, ("", 0, ""))[1] or None)

    canonical = {p: [int(c, 16) for c in d.split()] for p, (_, _, d) in data.items()
                 if d and not d.startswith("<") and not HANGUL_FIRST <= p <= HANGUL_LAST}

    def full(p):
        return [q for c in canonical[p] for q in (full(c) if c in canonical else [c])]

    decompositions, pool = [], []
    for p in sorted(canonical):
        expanded = full(p)
        decompositions.append((p, len(pool), len(expanded)))
        pool.extend(expanded)
    compositions = sorted((d[0], d[1], p) for p, d in canonical.items()
                          if len(d) == 2 and p not in excluded)

    hexes = lambda values: ", ".join(f"0x{v:X}" for v in values)
    lines = [
        "// Generated by tools/make_unicode_tables.py. Do not edit.",
        f"// From the Unicode Character Database {VERSION}: "
        + ", ".join(f"{n} (SHA-256 {h[:16]}...)" for n, h in SOURCES.items()) + ".",
        "// Unicode data © Unicode, Inc., used under the Unicode License v3:",
        "// https://www.unicode.org/license.txt",
        "",
        '#include "core/tokenizer/unicode_tables.h"',
        "",
        "namespace bllm::tokenizer::unicode_tables {",
        "namespace {",
        "",
        f"constexpr ClassRange kClasses[] = {{  // {len(classes)} ranges",
        *[f"    {{0x{a:X}, 0x{b:X}, CharClass::{c}}}," for a, b, c in classes],
        "};",
        "",
        f"constexpr CombiningRange kCombining[] = {{  // {len(combining)} ranges",
        *[f"    {{0x{a:X}, 0x{b:X}, {c}}}," for a, b, c in combining],
        "};",
        "",
        f"constexpr Decomposition kDecompositions[] = {{  // {len(decompositions)} characters",
        *[f"    {{0x{p:X}, {start}, {length}}}," for p, start, length in decompositions],
        "};",
        "",
        f"constexpr char32_t kDecompositionPool[] = {{  // {len(pool)} code points",
        *[f"    {hexes(pool[i:i + 8])}," for i in range(0, len(pool), 8)],
        "};",
        "",
        f"constexpr Composition kCompositions[] = {{  // {len(compositions)} pairs",
        *[f"    {{0x{a:X}, 0x{b:X}, 0x{c:X}}}," for a, b, c in compositions],
        "};",
        "",
        "}  // namespace",
        "",
        f'std::string_view version() noexcept {{ return "{VERSION}"; }}',
        "std::span<const ClassRange> classes() noexcept { return kClasses; }",
        "std::span<const CombiningRange> combining() noexcept { return kCombining; }",
        "std::span<const Decomposition> decompositions() noexcept { return kDecompositions; }",
        "std::span<const char32_t> decomposition_pool() noexcept { return kDecompositionPool; }",
        "std::span<const Composition> compositions() noexcept { return kCompositions; }",
        "",
        "}  // namespace bllm::tokenizer::unicode_tables",
    ]
    with open(sys.argv[1], "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(classes)} class ranges, {len(combining)} combining ranges, "
          f"{len(decompositions)} decompositions ({len(pool)} code points), "
          f"{len(compositions)} compositions", file=sys.stderr)


if __name__ == "__main__":
    main()
