# Generates a header of WGSL sources as inline constexpr string_views.
#
# Invoked at build time via `cmake -P`. Single-sources the shaders: the same
# .wgsl file is the only copy, and both build configurations compile the
# generated header. A native test asserts the generated constant is byte
# identical to the file on disk, so this cannot drift silently.
#
# Expects: -DOUTPUT=<path> -DSHADERS=<;-separated .wgsl paths>

set(DELIM "BLLMWGSL")
set(content "// Generated by cmake/embed_shaders_script.cmake. Do not edit.\n")
string(APPEND content "#pragma once\n\n#include <string_view>\n\n")
string(APPEND content "namespace bllm::shaders {\n\n")

foreach(shader IN LISTS SHADERS)
    if(NOT EXISTS "${shader}")
        message(FATAL_ERROR "embed_shaders: no such shader: ${shader}")
    endif()
    get_filename_component(name "${shader}" NAME_WE)
    file(READ "${shader}" source)

    # Fail loudly rather than emit a header that will not compile.
    string(FIND "${source}" ")${DELIM}\"" clash)
    if(NOT clash EQUAL -1)
        message(FATAL_ERROR
            "embed_shaders: ${shader} contains the raw-string delimiter )${DELIM}\". "
            "Change the delimiter in this script.")
    endif()

    string(APPEND content
        "inline constexpr std::string_view ${name} = R\"${DELIM}(${source})${DELIM}\";\n\n")
endforeach()

string(APPEND content "}  // namespace bllm::shaders\n")

# Only rewrite when the content actually changes, so unrelated rebuilds do not
# cascade through every translation unit that includes this header.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
